name: Chunk Build Status
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Resolve dependencies
        run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -Dmaven.repo.local=${{ runner.temp }}/.m2/repository
        working-directory: ./java
      - name: Validate chunk build configuration
        working-directory: ./java/build
        run: |
          CHUNKS_YAML=${{ github.workspace }}/.github/config/chunks.yaml
          MAVEN_PROJECT=${{ github.workspace }}/java
          mvn compile exec:java -q -e -Dexec.mainClass=sleeper.build.chunks.ValidateProjectChunks \
            -Dmaven.repo.local=${{ runner.temp }}/.m2/repository \
            -Dexec.args="$CHUNKS_YAML $MAVEN_PROJECT"
