name: Build Ingest Runner Module
on:
  push:
    paths:
      - '.github/workflows/chunk-ingest-runner.yaml'
      - '.github/workflows/chunk.yaml'
      - '.github/config/chunks.yaml'
      - 'code-style/checkstyle*.xml'
      - 'code-style/spotbugs*.xml'
      - 'java/pom.xml'
      - 'java/ingest/**'
      - 'java/common-job/**'
      - 'java/sketches/**'
      - 'java/tables/**'
      - 'java/statestore/**'
      - 'java/dynamodb-tools/**'
      - 'java/parquet/**'
      - 'java/configuration/**'
      - 'java/core/**'

jobs:
  module-workflow:
    uses: ./.github/workflows/chunk.yaml
    with:
      chunkId: ingest-runner
