name: Build Data Modules
on:
  push:
    paths:
      - '.github/workflows/chunk-data.yaml'
      - '.github/workflows/chunk.yaml'
      - '.github/config/chunks.yaml'
      - 'code-style/checkstyle*.xml'
      - 'code-style/spotbugs*.xml'
      - 'java/pom.xml'
      - 'java/tables/**'
      - 'java/garbage-collector/**'
      - 'java/metrics/**'
      - 'java/statestore/**'
      - 'java/parquet/**'
      - 'java/dynamodb-tools/**'
      - 'java/configuration/**'
      - 'java/core-arrow/**'
      - 'java/core/**'

jobs:
  chunk-workflow:
    uses: ./.github/workflows/chunk.yaml
    with:
      chunkId: data
