name: Build State Store Module
on:
  pull_request:
    paths:
      - '.github/workflows/chunk-statestore.yaml'
      - '.github/workflows/chunk.yaml'
      - '.github/config/chunks.yaml'
      - 'code-style/checkstyle*.xml'
      - 'code-style/spotbugs*.xml'
      - 'java/pom.xml'
      - 'java/statestore/**'
      - 'java/statestore-commit/**'
      - 'java/statestore-commit-lambda/**'
      - 'java/statestore-snapshot-lambda/**'
      - 'java/compaction/compaction-status-store/**'
      - 'java/compaction/compaction-core/**'
      - 'java/ingest/ingest-status-store/**'
      - 'java/ingest/ingest-core/**'
      - 'java/common/common-invoke-tables/**'
      - 'java/parquet/**'
      - 'java/configuration/**'
      - 'java/common/dynamodb-tools/**'
      - 'java/core/**'

jobs:
  chunk-workflow:
    uses: ./.github/workflows/chunk.yaml
    with:
      chunkId: statestore
