on:
  workflow_call:
    inputs:
      chunkId:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: java/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Resolve dependencies
        run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -Dmaven.repo.local=.m2/repository
        working-directory: ./java
      - name: Get chunk configuration
        id: config
        working-directory: ./java/build
        run: |
          mvn compile exec:java -q -Dexec.mainClass=sleeper.build.chunks.GetChunkConfig \
            -Dmaven.repo.local=../.m2/repository \
            -Dexec.args="${{ inputs.chunkId }} github_actions_outputs ${{ github.workspace }}/.github/config/chunks.yaml" \
            >> $GITHUB_OUTPUT
      - name: Compile
        run: mvn --batch-mode clean install -am -pl ${{ steps.config.outputs.moduleList }} -Pquick,skipShade -Dmaven.repo.local=.m2/repository
        working-directory: ./java
      - name: Test
        run: mvn --batch-mode --fail-at-end verify -pl ${{ steps.config.outputs.moduleList }} -Dmaven.repo.local=.m2/repository -e
        working-directory: ./java
      - name: Generate site
        if: always()
        run: |
          mvn --batch-mode site site:deploy -am -pl ${{ steps.config.outputs.moduleList }} \
            -Dmaven.repo.local=.m2/repository 
        working-directory: ./java
      - name: Upload site as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: |
            /tmp/sleeper/site
      - name: Upload surefire report as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-report.html
          path: |
            /tmp/sleeper/site/surefire-report.html
      - name: Upload failsafe report as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: failsafe-report.html
          path: |
            /tmp/sleeper/site/failsafe-report.html
      - name: Upload checkstyle report as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report.html
          path: |
            /tmp/sleeper/site/checkstyle-aggregate.html
