name: Build Clients Module
on:
  push:
    paths:
      - '.github/workflows/chunk-clients.yaml'
      - '.github/workflows/chunk.yaml'
      - '.github/config/chunks.yaml'
      - 'code-style/checkstyle*.xml'
      - 'code-style/spotbugs*.xml'
      - 'java/pom.xml'
      - 'java/clients/**'
      - 'java/query/**'
      - 'java/compaction-job-creation/**'
      - 'java/compaction-status-store/**'
      - 'java/ingest/ingest-status-store/**'
      - 'java/splitter/**'
      - 'java/sketches/**'
      - 'java/tables/**'
      - 'java/common-job/**'
      - 'java/compaction-core/**'
      - 'java/ingest/ingest-core/**'
      - 'java/statestore/**'
      - 'java/parquet/**'
      - 'java/dynamodb-tools/**'
      - 'java/configuration/**'
      - 'java/core/**'

jobs:
  chunk-workflow:
    uses: ./.github/workflows/chunk.yaml
    with:
      chunkId: clients
