name: Build Common Modules
on:
  push:
    paths:
      - '.github/workflows/chunk-common.yaml'
      - '.github/workflows/chunk.yaml'
      - '.github/config/chunks.yaml'
      - 'code-style/checkstyle*.xml'
      - 'code-style/spotbugs*.xml'
      - 'java/pom.xml'
      - 'java/build/**'
      - 'java/common-job/**'
      - 'java/dynamodb-tools/**'
      - 'java/parquet/**'
      - 'java/sketches/**'
      - 'java/configuration/**'
      - 'java/core/**'

jobs:
  module-workflow:
    uses: ./.github/workflows/chunk.yaml
    with:
      chunkId: common
