on:
  workflow_call:
    inputs:
      chunkId:
        required: true
        type: string
      publishTestReport:
        default: true
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: java/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Resolve Dependencies
        run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -Dmaven.repo.local=.m2/repository
        working-directory: ./java
      - name: Get chunk configuration
        id: config
        working-directory: ./java/build
        run: |
          get_property() {
            mvn compile exec:java -q -Dexec.mainClass=sleeper.build.chunks.GetChunkConfig \
              -Dmaven.repo.local=../.m2/repository \
              -Dexec.args="${{ inputs.chunkId }} $1 ${{ github.workspace }}/.github/config/chunks.yaml"
          }
          echo "chunkName=$(get_property name)" >> $GITHUB_OUTPUT
          echo "moduleList=$(get_property maven_project_list)" >> $GITHUB_OUTPUT
      - name: Compile
        run: mvn --batch-mode clean install -am -pl ${{ steps.config.outputs.moduleList }} -Pquick,skipShade -Dmaven.repo.local=.m2/repository
        working-directory: ./java
      - name: Test
        run: mvn --batch-mode --fail-at-end verify -pl ${{ steps.config.outputs.moduleList }} -Dmaven.repo.local=.m2/repository
        working-directory: ./java
      - name: Publish Test Report
        if: ${{ always() && inputs.publishTestReport }}
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Tests for ${{ steps.config.outputs.chunkName }}
      - name: Publish Checkstyle Report
        if: ${{ always() }}
        uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        with:
          path: '**/checkstyle-result.xml'
          name: Checkstyle for ${{ steps.config.outputs.chunkName }}
      - name: Publish Spotbugs Report
        if: ${{ always() }}
        uses: jwgmeligmeyling/spotbugs-github-action@v1.2
        with:
          path: '**/spotbugsXml.xml'
          name: Spotbugs for ${{ steps.config.outputs.chunkName }}
