name: Dependency Check
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: .m2/repository
          key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-dependency-check-
      - name: Resolve dependencies
        run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -Dmaven.repo.local=../.m2/repository
        working-directory: ./java
      - name: Explain disabled workflow
        run: echo "Temporarily disabled dependency checks as NVD API is unavailable."
      # - name: Update CVEs database
      #   run: mvn --batch-mode dependency-check:update-only -Dmaven.repo.local=../.m2/repository
      #   working-directory: ./java
      # - name: Build with Maven
      #   run: mvn --batch-mode verify dependency-check:aggregate -Pquick -Dmaven.repo.local=../.m2/repository
      #   working-directory: ./java
      # - name: Upload dependency check report
      #   if: ${{ always() }}
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: Dependency check report
      #     path: java/target/dependency-check-report.html
