name: Dependency Check Changes
on:
  push:
    paths:
      - '.github/workflows/dependency-check-changes.yaml'
      - '.github/workflows/dependency-check.yaml'
      - 'code-style/dependency-check-suppressions.xml'
      - 'java/**/pom.xml'

jobs:
  build-cli:
    uses: ./.github/workflows/dependency-check.yaml
