name: Bulk Import Docker
on:
  push:
    paths:
      - '.github/workflows/docker-bulk-import.yaml'
      - 'java/bulk-import-runner/docker/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: java/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Resolve dependencies
        run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -Dmaven.repo.local=.m2/repository
        working-directory: ./java
      - name: Compile
        run: mvn --batch-mode clean install -am -pl bulk-import/bulk-import-runner -Pquick -Dmaven.repo.local=.m2/repository
        working-directory: ./java
      - name: Copy .jar to docker directory
        run: cp target/bulk-import-runner-*-SNAPSHOT-utility.jar docker/bulk-import-runner.jar
        working-directory: ./java/bulk-import/bulk-import-runner
      - name: Docker build
        run: docker build .
        working-directory: ./java/bulk-import/bulk-import-runner/docker
