name: Docker CLI Deployment
on:
  push:
    branches:
      - main
      - 717-add-devcontainers-support
    tags:
      - v*

jobs:
  build-cli:
    uses: ./.github/workflows/docker-cli.yaml
    with:
      pushImages: true
