on:
  workflow_call:
    inputs:
      pushImages:
        default: false
        required: false
        type: boolean

env:
  DOCKER_PLATFORMS: linux/amd64,linux/arm64/v8
  DEPENDENCIES_IMAGE: sleeper-dependencies:current
  BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: java/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Resolve dependencies
        run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -Dmaven.repo.local=.m2/repository
        working-directory: ./java
      - name: Maven build
        run: ./scripts/build/buildForTest.sh package -Pquick --batch-mode -Dmaven.repo.local=.m2/repository
      - name: Environment Maven build
        run: ./scripts/cli/environment/buildMaven.sh package -Pquick --batch-mode -Dmaven.repo.local=../.m2/repository
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Plan build
        id: plan
        run: |
          ./.github/scripts/planCliBuild.sh \
            "${{ github.repository_owner }}" \
            "${{ github.ref }}"
      - name: Build Docker dependencies
        uses: docker/build-push-action@v4
        with:
          context: ./scripts/cli/dependencies
          push: true
          sbom: false
          provenance: false
          tags: ${{ env.DEPENDENCIES_IMAGE }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
          labels: |
            git-commit=${{ github.sha }}
            build-url=${{ env.BUILD_URL }}
          outputs: type=oci,dest=/tmp/dependencies-image.tar
      - name: Delete old images
        if: ${{ inputs.pushImages }}
        working-directory: ./java/build
        run: |
          echo "token=${{ secrets.GITHUB_TOKEN }}" >> delete.properties
          echo "organization=${{ github.repository_owner }}" >> delete.properties
          echo "packageNames=$GHCR_PACKAGE_NAMES" >> delete.properties
          echo "ignoreTagsPattern=^(latest|[0-9.]+)$" >> delete.properties
          echo "keepMostRecent=4" >> delete.properties
          mvn compile exec:java -q -e -Dexec.mainClass=sleeper.build.github.api.containers.DeleteGHCRVersions \
            -Dmaven.repo.local=../.m2/repository \
            -Dexec.args=delete.properties
      - name: Upload jars as artifact
        uses: actions/upload-artifact@v2
        with:
          name: scripts-jars
          path: ./scripts/jars
      - name: Upload environment jars as artifact
        uses: actions/upload-artifact@v2
        with:
          name: environment-jars
          path: ./scripts/cli/environment/jars
      - name: Upload dependencies image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dependencies-image
          path: /tmp/dependencies-image.tar
    outputs:
      builderTag: ${{ steps.plan.outputs.builderTag }}
      envTag: ${{ steps.plan.outputs.envTag }}
      deployTag: ${{ steps.plan.outputs.deployTag }}
      platforms: ${{ env.DOCKER_PLATFORMS }}
      buildUrl: ${{ env.BUILD_URL }}
  builder:
    needs: setup
    uses: ./.github/workflows/docker-cli-image.yaml
    with:
      pushImages: ${{ inputs.pushImages }}
      context: ./scripts/cli/builder
      pushTag: ${{ needs.setup.outputs.builderTag }}
      platforms: ${{ needs.setup.outputs.platforms }}
      buildUrl: ${{ needs.setup.outputs.buildUrl }}
  environment:
    needs: setup
    uses: ./.github/workflows/docker-cli-image.yaml
    with:
      pushImages: ${{ inputs.pushImages }}
      context: ./scripts/cli/environment
      pushTag: ${{ needs.setup.outputs.envTag }}
      platforms: ${{ needs.setup.outputs.platforms }}
      buildUrl: ${{ needs.setup.outputs.buildUrl }}
  deployment:
    needs: setup
    uses: ./.github/workflows/docker-cli-image.yaml
    with:
      pushImages: ${{ inputs.pushImages }}
      context: ./scripts
      pushTag: ${{ needs.setup.outputs.deployTag }}
      platforms: ${{ needs.setup.outputs.platforms }}
      buildUrl: ${{ needs.setup.outputs.buildUrl }}
