name: Docker CLI Build
on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v*
    paths:
      - '.github/workflows/docker-cli.yaml'
      - '.github/scripts/planCliBuild.sh'
      - 'scripts/Dockerfile'
      - 'scripts/.dockerignore'
      - 'scripts/cli/**'

jobs:
  chunk-workflow:
    uses: ./.github/workflows/docker-cli.yaml
    with:
      pushImages: false
