name: Build CDK Custom Resources Module
on:
  push:
    paths:
      - '.github/workflows/module-cdk-custom-resources.yaml'
      - '.github/workflows/module.yaml'
      - 'java/cdk-custom-resources/**'
      - 'java/tables/**'
      - 'java/statestore/**'
      - 'java/parquet/**'
      - 'java/configuration/**'
      - 'java/core/**'

jobs:
  module-workflow:
    uses: ./.github/workflows/module.yaml
    with:
      module: cdk-custom-resources
