on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
      - name: Compile
        run: mvn --batch-mode clean install -am -pl ${{ inputs.module }} -Pquick,skipShade
        working-directory: ./java
      - name: Test
        run: mvn --batch-mode verify -pl ${{ inputs.module }}
        working-directory: ./java
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Test Report for ${{ inputs.module }}
      - name: Publish Checkstyle Report
        if: ${{ always() }}
        uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        with:
          path: '**/checkstyle-result.xml'
          name: Checkstyle for ${{ inputs.module }}
