name: Build Compaction Job Execution Module
on:
  push:
    paths:
      - '.github/workflows/module-compaction-job-execution.yaml'
      - '.github/workflows/module.yaml'
      - 'java/pom.xml'
      - 'java/compaction-job-execution/**'
      - 'java/compaction-job-creation/**'
      - 'java/ingest/**'
      - 'java/common-job/**'
      - 'java/sketches/**'
      - 'java/tables/**'
      - 'java/statestore/**'
      - 'java/parquet/**'
      - 'java/configuration/**'
      - 'java/core/**'

jobs:
  module-workflow:
    uses: ./.github/workflows/module.yaml
    with:
      module: compaction-job-execution
