name: Rust Incremental Build
on:
  workflow_dispatch: # Allow manual running to refresh/check cache
  schedule: # Planned execution once per day
    - cron: "0 2 * * *"
  pull_request:
    paths:
      - '.github/workflows/rust-cache.yaml'

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  SSCACHE_CACHE_SIZE: "2G"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.79.0
      - uses: mozilla-actions/sccache-action@v0.0.5
      - name: Install cargo cross
        run: cargo install cross
      - name: Build Rust
        working-directory: ./rust
        run: cross build --target x86_64-unknown-linux-gnu
