name: Test Scripts
on:
  push:
    paths:
      - '.github/workflows/scripts.yaml'
      - 'scripts/functions/**'

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: scripts/functions/runAllTests.sh
